apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: python-api-ns
  labels:
    app: python-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: python-api
